version: '2'
services:
    mlccc-app:
        image: mlccc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mlccc-postgresql:5432/mlccc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mlccc-postgresql:
        extends:
            file: postgresql.yml
            service: mlccc-postgresql
